## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/pitstop-helm-config

trigger:
  tags:
    include:
    - "*"
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main

extends:
  template: pipelines/build-bff/v1.yml@templates
  parameters:
    gitVersionSpec: '6.0.x'
    buildProject: src/Spydersoft.PitStop.Frontend/Spydersoft.PitStop.Frontend.csproj
    publishProject: src/Spydersoft.PitStop.Frontend/Spydersoft.PitStop.Frontend.csproj
    uiSourceDirectory: src/pitstop-ui
    artifactName: pitstop-web
    netCoreVersion: "10.0.x"
    artifactZipName: Spydersoft.PitStop.Frontend
    dockerImageName: spydersoft-consulting/pitstop-web
    dockerFilePath: Dockerfile
    containerRegistryName: github-spydersoft-docker
    imageTagVariableName: pitstop_web
    helmfileRepoName: helmfileconfig
    externalFeedCredentials: SpydersoftGithub
    #if it's a PR or build from main, don't update helmfile config or build/publish docker image
    ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
      bffExecuteSonar: true
      uiExecuteSonar: true
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
      bffExecuteSonar: false
      uiExecuteSonar: false

    bffExecuteTests: false
    bffUseSonarCloud: true
    bffSonarCloudOrganization: spydersoft-consulting
    bffSonarEndpointName: sonarcloud-spydersoft
    bffSonarProjectName: pitstop-web-bff
    bffSonarProjectKey: spydersoft-consulting_pitstop-web-bff
    bffSonarExtraProperties: |
      sonar.projectKey=spydersoft-consulting_pitstop-web-bff
      sonar.sources=**/src/Spydersoft.PitStop.Frontend/
      sonar.exclusions=**/src/pitstop-ui/**/*
      sonar.scanner.scanAll=false
      sonar.coverage.exclusions=**/*Program.cs,**/*Controller.cs

    uiSonarEndpointName: sonarcloud-spydersoft
    uiSonarCloudOrganization: spydersoft-consulting
    uiUseSonarCloud: true
    uiSonarConfigFile: react-sonar-project.properties
    uiCodeCoverageFile: src/pitstop-ui/output/coverage/cobertura-coverage.xml
    uiUnitTestFile: src/pitstop-ui/output/test/junit.xml
